export const getAllPrinciples = () => [
  'Vegan',
  'Vegeterian',
  'Pescatarian',
  'Gluten free',
  'Nut free',
  'Lactose free',
  'Halal',
  'Organic',
  'Eco friendly',
  'Local products',
  'No sugar',
  'No sodium',
  'Fair trade',
  'Package free',
  'Recyclable',
  'Compostable',
]
