export enum EventType {
  USER_SCANNED_BARCODE = 'USER_SCANNED_BARCODE',
  USER_SELECTED_PRINCIPLES = 'USER_SELECTED_PRINCIPLES',
  USER_LEFT_FEEDBACK = 'USER_LEFT_FEEDBACK',
  BARCODE_GOT_PROCESSED = 'BARCODE_GOT_PROCESSED',
}
