platform :ios do
  private_lane :setup_project do
    create_keychain(
      name: "actiontest_keychain",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end
  lane :internal do
    create_keychain
    match(
      type: 'appstore',
      keychain_name: "actiontest_keychain"
    )
    build_app(scheme: 'Symbio', workspace:'./ios/Symbio.xcworkspace', export_method: 'app-store')
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

platform :android do
  lane :internal do
    gradle(task: 'bundle', build_type: 'release', project_dir: 'android/')
    supply(track: 'internal', release_status: 'draft',)
  end
end
