name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: node --version
      - run: yarn test
