name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: Log versions
        run: |
          node --version
          npm --version
          yarn --version
      - run: yarn build
      - run: yarn test
