name: Test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v1
      - name: Recreate env.dev.ts
        run: echo "${{secrets.REACT_NATIVE_APP_ENV_DEV}}" | base64 -d > react-native-app/env.dev.ts
      - uses: bahmutov/npm-install@v1
      - name: Log versions
        run: |
          node --version
          npm --version
          yarn --version
      - run: yarn build
      - run: cd react-native-app && yarn test -t "authContext"
      - run: cd react-native-app && yarn test -t "ScanBarcodeScreen"
      - run: cd react-native-app && yarn test -t "ScanBarcodeView"
      - run: cd react-native-app && yarn test -t "ScanBarcodeViewContainer"
      - run: cd react-native-app && yarn test -t "FeedbackScreen"
      - run: cd react-native-app && yarn test -t "FeedbackView"
      - run: cd react-native-app && yarn test -t "useObservable"
      - run: cd react-native-app && yarn test -t "ObservableView"
      - run: cd react-native-app && yarn test -t "Timeout"
      - run: cd react-native-app && yarn test -t "observeMessages"
      - run: cd react-native-app && yarn test -t "observeTokens"
      - run: cd react-native-app && yarn test -t "messagingContext"
      - run: cd react-native-app && yarn test -t "createSwipableModal"
      - run: cd react-native-app && yarn test -t "Interactable"
      - run: cd react-native-app && yarn test -t "Navigation"
      - run: cd react-native-app && yarn test -t "PrincipleView"
      - run: cd react-native-app && yarn test -t "SetupPrinciplesScreen"
      - run: cd react-native-app && yarn test -t "SetupPrinciplesView"
      - run: cd react-native-app && yarn test -t "SetupPrinciplesViewContainer"
      - run: cd react-native-app && yarn test -t "ProductNotFound"
      - run: cd react-native-app && yarn test -t "ProductScreen"
      - run: cd react-native-app && yarn test -t "ProductView"
      - run: cd react-native-app && yarn test -t "ProductViewContainer"
      - run: cd react-native-app && yarn test -t "Button"
      - run: cd react-native-app && yarn test -t "CloseButton"
      - run: cd react-native-app && yarn test -t "CloseButtonView"
      - run: cd react-native-app && yarn test -t "ErrorView"
      - run: cd react-native-app && yarn test -t "Icon"
      - run: cd react-native-app && yarn test -t "Loading"
      - run: cd react-native-app && yarn test -t "Modal"
      - run: cd react-native-app && yarn test -t "RoundedButton"
      - run: cd react-native-app && yarn test -t "TimeoutView"
